apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    prometheus.io/scrape: 'true'
  name: house-price
  namespace: kserve-inference
spec:
  predictor:
    model:
      modelFormat:
        name: mlflow
      protocolVersion: v2
      storageUri: s3://mlflow/9/dc7159eecdd04337919215f3a3234062/artifacts/lgbm-house
    serviceAccountName: kserve-sa
